### ISSUE TITLE
No active Reality Toolkit dialog while building a project

### ISSUE THREAD

**Issue by FejZa** [realitycollective/realitytoolkit.dev#11]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

Sometimes while building a project this dialog will keep popping up all the time no matter what you press

![image](https://user-images.githubusercontent.com/9565734/159169807-0ecb3b8b-c019-4854-9dfb-f756626546ca.png)

**Comment by SimonDarksideJ** [comment]
Can you add a little more detail @FejZa , such as the setup for your scene and any other potential replication steps?

**Comment by FejZa** [comment]
Hasn't been seen more than once and not able to reproduce. Closed.
