### ISSUE TITLE
OpenVR / UnityInput configuration enabled by default and has errors

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#14]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

Currently the OpenVR and Unity Input platforms are enabled by default, this used to be a good standard but is no longet the case and can cause issues when testing platforms such as Meta via Link.

## To Reproduce

1. Create a new Unity Project
2. Import Core package via OpenUPM
3. Configure scene
4. Run project
5. See errors

## Your Setup

- **Operating System:**

    - [X] Windows
    - [ ] MacOs
    - [ ] Linux
    - [ ] Other

- **Target Platforms:**

    - [ ] WindowsXR
    - [ ] HoloLens
    - [X] Meta Quest
    - [ ] Pico
    - [ ] Other (please specifiy)

- **Unity Version:** 
 

 - 2020.3.30f

- **Packages**
    - [X] com.realitytoolkit.core 1.0.0.Preview.1

**Comment by FejZa** [comment]
The OpenVR module has been removed from the toolkit with the Service Framework migration.
