### ISSUE TITLE
Warnings raised about the REST client using obsolete features.

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#16]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

Will fill in later

Packages\com.xrealitylabs.xrfoundation\Runtime\Utilities\Rest.cs(356,17): warning CS0618: 'UnityWebRequest.isNetworkError' is obsolete: 'UnityWebRequest.isNetworkError is deprecated. Use (UnityWebRequest.result == UnityWebRequest.Result.ConnectionError) instead.'

## Your Setup

- **Operating System:**

    - [ ] Windows
    - [ ] MacOs
    - [ ] Linux
    - [ ] Other

- **Target Platforms:**

    - [ ] WindowsXR
    - [ ] HoloLens
    - [ ] Meta Quest
    - [ ] Pico
    - [ ] Other (please specifiy)

- **Unity Version:** 
 

 - 2020.3.30f

- **Packages**
    - [ ] com.realitytoolkit.core 1.0.0.Preview.2 
    - [ ] com.realitytoolkit.metaplatform 1.0.0.Preview.2

**Comment by FejZa** [comment]
This is not even a RTK package the error is raised in?

**Comment by SimonDarksideJ** [comment]
Apologies, you are correct, this is not a RealityToolkit issue, my bad
