### ISSUE TITLE
Feature Request: Locomotion Systems Research

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#3]
Posted by a user on the MRTK, worth checking out

> Here are some locomotion systems that might be useful to look to get ideas of what kind of locomotion to implement for VR.
Locomotion Vault
Database, created by Microsoft, of over 100 locomotion techniques, but no implementations.
GitHub: https://locomotionvault.github.io/
Paper: https://www.microsoft.com/en-us/research/publication/locomotion-vault-the-extra-mile-in-analyzing-vr-locomotion-techniques/
An Evaluation Testbed for Locomotion in Virtual Reality
Locomotion methods implemented: Arm swinging, Walking-in-place (WIP), Cyberith’s Virtualizer, Joystick.
GitHub: https://github.com/VRatPolito/LET-VR
Paper: https://dx.doi.org/10.1109/TVCG.2020.3032440
Video of Locomotion methods: https://www.dropbox.com/sh/82fw7i277oo0fef/AACl-FxRi6imX7NUpbYIpEhCa/Training?dl=0&subfolder_nav_tracking=1
Scenarios (tasks): https://www.dropbox.com/sh/82fw7i277oo0fef/AABWOcbEH2ReGD4JK8ZeHNmAa/Scenarios?dl=0&subfolder_nav_tracking=1
Redirected Walking Locomotion Techniques Toolkit
GitHub: https://github.com/USC-ICT-MxR/RDWT
Paper: https://ieeexplore.ieee.org/document/7859537
XinReality - Locomotion
A database of Locomotion techniques, similar to Locomotion Vault, but there are some links to source code of the locomotion techniques.
Website: https://xinreality.com/wiki/Locomotion
Travrsal
GitHub: https://github.com/WetzoldStudios/traVRsal-sdk
Website: https://www.travrsal.com/
I hope this helps.

**Comment by FejZa** [comment]
How is this a feature request? I have looked at most of these sources while working on the locomotion system but we can not provide all of them out of the box. The system does support implementing them as custom locomotion providers though.

**Comment by FejZa** [comment]
Has been researched when implementing the locomotion system.
