### ISSUE TITLE
Feature Request: Make the Service Runtime Inspector editable to allow Runtime manipulation of a service for testing

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#40]
# Reality Collective - Reality Toolkit Bug Report

## Describe the feature

Feature Request: Make the Service Runtime Inspector editable to allow Runtime manipulation of a service for testing

**Comment by FejZa** [comment]
This is quite the heavy undertaking with a lot of pitfalls. Not sure it is worth the effort and we want to go this route. Testing a service at runtime with different configurations should be something you do by using different profiles or custom debug logic.

**Comment by SimonDarksideJ** [comment]
It is merely an extension of the Service Display Hook, to allow for updates to config while it is running in the editor only. Will update request to clarify.
It is a fairly low priority request at this point and should be migrated to the Service Framework package.

**Comment by SimonDarksideJ** [comment]
Migrated to - https://github.com/realitycollective/com.realitycollective.service-framework/issues/57
