### ISSUE TITLE
Focus System needs evaluation

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#43]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

Currently the focus system is embedded within the Input system and always on by default, which is not ideal.

This currently causes several architectural issues related to how it is initialised and utilised.

Ideally, focus should be an independent component which the Input System or related components can call upon IF focus is required and configured for.

## Expected behavior

The Focus system should be an independent component, configurable and only available when required.  To ensure it is initialised separately and properly.

## Actual behavior

Focus is embedded in the InputSystem, initialised out of order before all services are actually registered and NOT independent.

**Comment by FejZa** [comment]
The focus provider has been refactored to be a regular data provider to the input system, giving more control to the dev in regard to when and if it is registered.
