### ISSUE TITLE
[Service Framework] Create data provider wizard has no way of creating a profile for the provider

### ISSUE THREAD

**Issue by FejZa** [realitycollective/realitytoolkit.dev#46]
# Reality Collective - Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

When generating a new data provider using the wizard, there is no way to have a profile generated for the new provider together with the interface and implementation.

## How would you classify your suggestion

It's better.

## Describe the solution you'd like

What I said above.

## Describe alternatives you've considered

None. Just do it.

**Comment by SimonDarksideJ** [comment]
Sure, we'll enhance the generator to include a profile.  
And also update the main service generator to make having a profile optional too
