### ISSUE TITLE
Inspectors render duplicate content for toolkit profiles

### ISSUE THREAD

**Issue by FejZa** [realitycollective/realitytoolkit.dev#56]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

Service inspectors for the toolkit core services render duplicate content since framework migration:

![image](https://user-images.githubusercontent.com/9565734/191314642-7116d0c0-b891-4878-8a43-7074fd23c426.png)

**Comment by SimonDarksideJ** [comment]
Replicated, seems to affect:
* Camera System
* Boundary System
* Spatial Awareness system

Oddly it does not affect the Input system or Locomotion System
