### ISSUE TITLE
Console spammed with "Already attempting to reset the root profile!" warning

### ISSUE THREAD

**Issue by FejZa** [realitycollective/realitytoolkit.dev#57]
# Reality Collective - Reality Toolkit Bug Report

## Describe the bug

With the latest toolkit release the console keeps logging
"Already attempting to reset the root profile!"

whenever a change to configuration is made.

**Comment by SimonDarksideJ** [comment]
Unable to replicate @FejZa , can you provide more detailed replication steps in an upgraded or clean repo?

I tested:
* New project
* Added package through OpenUPM CLI
* Ran "Reality Collective -> Configure"
* Played around with settings in multiple services, including a new test service.
No errors logged.

**Comment by FejZa** [comment]
This has been fixed in a recent release.
