### ISSUE TITLE
Investigate removing reflection from Core libraries and libs

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#6]
# Reality Collective - Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

Unity 2021 has completely broken reflection for IL2CPP builds and it does nto look like it is going to be fixed any time soon.  Unity 2020 still works as expected but all future builds are farked

## How would you classify your suggestion

- Architecture / Services

## Describe the solution you'd like

Investigate the cost and impact of removing reflection where possible from the Framework, especially use of System.Type.Guid references and lookups

## Describe alternatives you've considered

Not using Unity 2021 or above.  But not really a solution.  Mono works but is not publishable to the Unity Store.

## Additional context

* https://issuetracker.unity3d.com/issues/missingmethodexception-in-player-dot-log-when-calling-type-dot-guid-in-il2cpp-build
Unity logged issue regarding use of System GUID's.  The fixed the exception BUT NOT the actual problem, which causes apps to freeze.

**Comment by FejZa** [comment]
Reflection is fixed in the latest Unity / toolkit release.
