### ISSUE TITLE
The Service Framework should support the Dependency Injection pattern of defining Interfaces as dependencies

### ISSUE THREAD

**Issue by SimonDarksideJ** [realitycollective/realitytoolkit.dev#64]
# Reality Collective - Reality Toolkit Feature Request

## Is your feature request related to a problem? Please describe

The Dependency Injection Pattern defines a method where at design time, the developer can define the interfaces that a service needs in order to properly instantiate
https://learn.microsoft.com/en-us/dotnet/core/extensions/dependency-injection

This controls the order in which services instantiate and enable tighter "loosely coupled" integration between services and ensures a dependent service is available to wire up events when a service starts.

## How would you classify your suggestion

- Architecture / Services

## Describe the solution you'd like

The ability to define service interface dependencies in the design of a service and have the service framework automatically recognise the dependency on startup.

## Describe alternatives you've considered

Manual

**Comment by FejZa** [comment]
This is definitely something we must look into.

**Comment by SimonDarksideJ** [comment]
Migrated to:
https://github.com/realitycollective/com.realitycollective.service-framework/issues/58
